# Generated by Django 3.1.3 on 2020-12-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_form', '0002_auto_20201201_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='offers',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='offers',
            name='slug',
            field=models.SlugField(default=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='bonus',
            field=models.FloatField(db_index=True, max_length=3),
        ),
        migrations.AlterIndexTogether(
            name='offers',
            index_together={('id', 'slug')},
        ),
        migrations.RemoveField(
            model_name='offers',
            name='end_date',
        ),
    ]
