# Generated by Django 3.1.3 on 2020-12-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_form', '0003_auto_20201205_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
