# Generated by Django 3.1.3 on 2020-12-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_form', '0005_auto_20201207_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
