# Generated by Django 3.1.3 on 2020-12-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_form', '0007_auto_20201208_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
